language: python
os: linux
dist: focal
python:
    - "3.8"
before_install:
    - sudo apt-get install -y libssl-dev libcurl4-openssl-dev
    - pip install codecov
    - pip install pytest-cov
install:
    - pip install .
script:
    - py.test -vv --cov-report=term --cov=cvescan
after_success:
    codecov
