name: cvescan
base: core18
version: '1.2.01'
summary: Security/CVE vulnerability monitoring for Ubuntu
license: GPL-3.0
description: |
  A script and XSLT file that use OpenSCAP and OVAL files from the
  Ubuntu Security Teamto output a plain text list of CVE vulnerabilities
  that exist for currently supported Ubuntu systems or for Ubuntu
  images (using a package manifest file).
  
  Installation -> `sudo snap install cvescan`

  Usage Information -> `cvescan -h`

grade: stable
confinement: strict

plugs:
  apt-dpkg-db:
    interface: system-files
    read: 
    - /var/lib/snapd/hostfs/var/lib/dpkg
    - /var/lib/snapd/hostfs/var/cache/apt
    - /etc/apt
    - /etc/dpkg
  ua-status:
    interface: system-files
    read: 
    - /var/lib/snapd/hostfs/var/lib/ubuntu-advantage

layout:
  /usr/lib/x86_64-linux-gnu/openscap:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/openscap
  /usr/share/dpkg:
    bind: $SNAP/usr/share/dpkg
  /usr/share/openscap:
    bind: $SNAP/usr/share/openscap
  /usr/bin/dpkg:
    bind-file: $SNAP/usr/bin/dpkg
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP/etc/dpkg/dpkg.cfg


apps:
  py:
    command: bin/cvescan
    environment:
      PATH: $PATH:$SNAP/usr/local/sbin:$SNAP/usr/local/bin:$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/snap/bin
      APT_CONFIG: $SNAP/etc/apt.conf
    plugs:
    - home
    - network
    - apt-dpkg-db
    - ua-status
  sh:
    command: ./cvescan.sh
    environment:
      PATH: $PATH:$SNAP/usr/local/sbin:$SNAP/usr/local/bin:$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/snap/bin
      APT_CONFIG: $SNAP/etc/apt.conf
    plugs:
    - home
    - network
    - apt-dpkg-db
  cvescan:
    command: ./cvescan.sh
    environment:
      PATH: $PATH:$SNAP/usr/local/sbin:$SNAP/usr/local/bin:$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/snap/bin
      APT_CONFIG: $SNAP/etc/apt.conf
    plugs:
    - home
    - network
    - apt-dpkg-db

parts:
  cvescan-python:
    plugin: python
    stage-packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - python3-apt
    source: .
  cvescan-bash:
    plugin: dump
    source: snapcraft/
    stage-packages:
      - grep
      - dpkg
      - libopenscap8
      - debianutils
      - xsltproc
      - coreutils
      - curl
      - bzip2
